#USE musimundos
#Trabalhando com o AS

#SELECT titulo AS T 
#FROM albuns AS A
#WHERE titulo LIKE 'b%';

#Trabalhando com LIMIT (LIMITA A QUANTIDADE DE CONSULTA QUE PRECISO, NESTE EXEMPLO EU PEDI AS 10 PRIMEIRAS POSICOES
# OFFSET (A PARTIR DE, NESTE EXEMPLO ABAIXO EU SOLICITO QUE, AS 10 PRIMEIRAS POSICOES, SEJAM EXIBIDAS/CONSULTADAS
#A PARTIR DA 10 POSIÇÃO

SELECT id, nome N, preco_unitario'TOP10'
FROM cancoes
ORDER BY preco_unitario DESC
LIMIT 10
OFFSET 10;